language: node_js
node_js:
  - 12
  - 10
  - 8

install:
  - npm install -g mocha # this should be installed from devDependencies
  - npm install -g chai # this should be installed from devDependencies
  - npm install -g nyc # this should be installed from devDependencies
  - npm install -g codecov
script:
  - npm run coverage
  - npm run report-coverage